[package]
authors = ["RundownRhino <52856631+RundownRhino@users.noreply.github.com>"]
edition = "2021"
name = "region_scanner"
version = "0.1.4"
description = "A CLI program to scan Minecraft region files and create Just Enough Resources world-gen.json files from the results. Tested on 1.16."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["cargo"] }
fastanvil = "0.26.0"
fastnbt = "2.1.0"
indoc = "1.0.6"
itertools = "0.10.3"
rayon = "1.5.3"
serde = "1.0.137"
serde_json = "1.0.81"
